[package]
name = "ewidencja-ozipz"
version = "1.2.1"
description = "Ewidencja OZiPZ – Oświata Zdrowotna i Promocja Zdrowia (Państwowa Inspekcja Sanitarna)"
authors = ["Sekcja OZiPZ"]
edition = "2021"

[lib]
name = "ewidencja_ozipz_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-sql = { version = "2", features = ["sqlite"] }
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
chrono = "0.4"
sqlx = { version = "0.8.6", default-features = false, features = ["sqlite", "runtime-tokio"] }
tauri-plugin-updater = "2"
tauri-plugin-process = "2"
