import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const rawSchedules = [
  {
    "id": "better-oz-schedule-9",
    "year": 2026,
    "month": 1,
    "monthName": "Styczeń",
    "title": "Dystrybucja",
    "jrwa": "966.14",
    "activityId": "FcAXA6DDS8yv3MXwRuXO",
    "activityName": "Dystrybucja",
    "plannedCount": 1,
    "completedCount": 1,
    "status": "done",
    "statusLabel": "Wykonane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-8",
    "year": 2026,
    "month": 1,
    "monthName": "Styczeń",
    "title": "Konkurs (quiz)",
    "jrwa": "966.1",
    "activityId": "aFuBdGdK1lOqoMdldAoG",
    "activityName": "Konkurs (quiz)",
    "plannedCount": 1,
    "completedCount": 0,
    "status": "done",
    "statusLabel": "Wykonane",
    "manuallyCompleted": true,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-10",
    "year": 2026,
    "month": 1,
    "monthName": "Styczeń",
    "title": "Konkurs (quiz)",
    "jrwa": "966.14",
    "activityId": "aFuBdGdK1lOqoMdldAoG",
    "activityName": "Konkurs (quiz)",
    "plannedCount": 1,
    "completedCount": 0,
    "status": "planned",
    "statusLabel": "Planowane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-11",
    "year": 2026,
    "month": 1,
    "monthName": "Styczeń",
    "title": "Pismo (list intencyjny)",
    "jrwa": "966.14",
    "activityId": "yyiNOcRBIps8O4GYDxWV",
    "activityName": "Pismo (list intencyjny)",
    "plannedCount": 1,
    "completedCount": 2,
    "status": "done",
    "statusLabel": "Wykonane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-12",
    "year": 2026,
    "month": 1,
    "monthName": "Styczeń",
    "title": "Prelekcja (warsztat)",
    "jrwa": "966.14",
    "activityId": "gW1kLj7owM5ebXSkmndz",
    "activityName": "Prelekcja (warsztat)",
    "plannedCount": 1,
    "completedCount": 6,
    "status": "done",
    "statusLabel": "Wykonane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-13",
    "year": 2026,
    "month": 1,
    "monthName": "Styczeń",
    "title": "Publikacja media (Strona)",
    "jrwa": "966.14",
    "activityId": "AehvrjZ6hmuzcGNydgGM",
    "activityName": "Publikacja media (Strona)",
    "plannedCount": 1,
    "completedCount": 10,
    "status": "done",
    "statusLabel": "Wykonane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-15",
    "year": 2026,
    "month": 2,
    "monthName": "Luty",
    "title": "Dystrybucja",
    "jrwa": "966.14",
    "activityId": "FcAXA6DDS8yv3MXwRuXO",
    "activityName": "Dystrybucja",
    "plannedCount": 1,
    "completedCount": 2,
    "status": "done",
    "statusLabel": "Wykonane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-19",
    "year": 2026,
    "month": 2,
    "monthName": "Luty",
    "title": "Dystrybucja",
    "jrwa": "966.3",
    "activityId": "FcAXA6DDS8yv3MXwRuXO",
    "activityName": "Dystrybucja",
    "plannedCount": 1,
    "completedCount": 1,
    "status": "done",
    "statusLabel": "Wykonane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-14",
    "year": 2026,
    "month": 2,
    "monthName": "Luty",
    "title": "Konkurs (quiz)",
    "jrwa": "966.1",
    "activityId": "aFuBdGdK1lOqoMdldAoG",
    "activityName": "Konkurs (quiz)",
    "plannedCount": 1,
    "completedCount": 0,
    "status": "done",
    "statusLabel": "Wykonane",
    "manuallyCompleted": true,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-16",
    "year": 2026,
    "month": 2,
    "monthName": "Luty",
    "title": "Konkurs (quiz)",
    "jrwa": "966.14",
    "activityId": "aFuBdGdK1lOqoMdldAoG",
    "activityName": "Konkurs (quiz)",
    "plannedCount": 1,
    "completedCount": 0,
    "status": "done",
    "statusLabel": "Wykonane",
    "manuallyCompleted": true,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-17",
    "year": 2026,
    "month": 2,
    "monthName": "Luty",
    "title": "Prelekcja (warsztat)",
    "jrwa": "966.14",
    "activityId": "gW1kLj7owM5ebXSkmndz",
    "activityName": "Prelekcja (warsztat)",
    "plannedCount": 1,
    "completedCount": 1,
    "status": "done",
    "statusLabel": "Wykonane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-20",
    "year": 2026,
    "month": 2,
    "monthName": "Luty",
    "title": "Prelekcja (warsztat)",
    "jrwa": "966.3",
    "activityId": "gW1kLj7owM5ebXSkmndz",
    "activityName": "Prelekcja (warsztat)",
    "plannedCount": 1,
    "completedCount": 1,
    "status": "done",
    "statusLabel": "Wykonane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-18",
    "year": 2026,
    "month": 2,
    "monthName": "Luty",
    "title": "Publikacja media (Strona)",
    "jrwa": "966.14",
    "activityId": "AehvrjZ6hmuzcGNydgGM",
    "activityName": "Publikacja media (Strona)",
    "plannedCount": 1,
    "completedCount": 1,
    "status": "done",
    "statusLabel": "Wykonane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-25",
    "year": 2026,
    "month": 3,
    "monthName": "Marzec",
    "title": "Dystrybucja",
    "jrwa": "966.18",
    "activityId": "FcAXA6DDS8yv3MXwRuXO",
    "activityName": "Dystrybucja",
    "plannedCount": 1,
    "completedCount": 0,
    "status": "planned",
    "statusLabel": "Planowane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-28",
    "year": 2026,
    "month": 3,
    "monthName": "Marzec",
    "title": "Dystrybucja",
    "jrwa": "966.3",
    "activityId": "FcAXA6DDS8yv3MXwRuXO",
    "activityName": "Dystrybucja",
    "plannedCount": 1,
    "completedCount": 0,
    "status": "planned",
    "statusLabel": "Planowane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-21",
    "year": 2026,
    "month": 3,
    "monthName": "Marzec",
    "title": "Konkurs (quiz)",
    "jrwa": "966.1",
    "activityId": "aFuBdGdK1lOqoMdldAoG",
    "activityName": "Konkurs (quiz)",
    "plannedCount": 1,
    "completedCount": 0,
    "status": "done",
    "statusLabel": "Wykonane",
    "manuallyCompleted": true,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-23",
    "year": 2026,
    "month": 3,
    "monthName": "Marzec",
    "title": "Pismo (list intencyjny)",
    "jrwa": "966.12",
    "activityId": "yyiNOcRBIps8O4GYDxWV",
    "activityName": "Pismo (list intencyjny)",
    "plannedCount": 1,
    "completedCount": 0,
    "status": "planned",
    "statusLabel": "Planowane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-22",
    "year": 2026,
    "month": 3,
    "monthName": "Marzec",
    "title": "Prelekcja (warsztat)",
    "jrwa": "966.1",
    "activityId": "gW1kLj7owM5ebXSkmndz",
    "activityName": "Prelekcja (warsztat)",
    "plannedCount": 1,
    "completedCount": 0,
    "status": "planned",
    "statusLabel": "Planowane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-26",
    "year": 2026,
    "month": 3,
    "monthName": "Marzec",
    "title": "Prelekcja (warsztat)",
    "jrwa": "966.18",
    "activityId": "gW1kLj7owM5ebXSkmndz",
    "activityName": "Prelekcja (warsztat)",
    "plannedCount": 1,
    "completedCount": 2,
    "status": "done",
    "statusLabel": "Wykonane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-29",
    "year": 2026,
    "month": 3,
    "monthName": "Marzec",
    "title": "Prelekcja (warsztat)",
    "jrwa": "966.3",
    "activityId": "gW1kLj7owM5ebXSkmndz",
    "activityName": "Prelekcja (warsztat)",
    "plannedCount": 1,
    "completedCount": 0,
    "status": "planned",
    "statusLabel": "Planowane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-30",
    "year": 2026,
    "month": 3,
    "monthName": "Marzec",
    "title": "Prelekcja (warsztat)",
    "jrwa": "966.5",
    "activityId": "gW1kLj7owM5ebXSkmndz",
    "activityName": "Prelekcja (warsztat)",
    "plannedCount": 1,
    "completedCount": 2,
    "status": "done",
    "statusLabel": "Wykonane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-31",
    "year": 2026,
    "month": 3,
    "monthName": "Marzec",
    "title": "Prelekcja (warsztat)",
    "jrwa": "966.6",
    "activityId": "gW1kLj7owM5ebXSkmndz",
    "activityName": "Prelekcja (warsztat)",
    "plannedCount": 1,
    "completedCount": 0,
    "status": "planned",
    "statusLabel": "Planowane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-24",
    "year": 2026,
    "month": 3,
    "monthName": "Marzec",
    "title": "Publikacja media (Facebook)",
    "jrwa": "966.12",
    "activityId": "h7fyjzUQfm50b8GiO2Cu",
    "activityName": "Publikacja media (Facebook)",
    "plannedCount": 1,
    "completedCount": 0,
    "status": "planned",
    "statusLabel": "Planowane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-27",
    "year": 2026,
    "month": 3,
    "monthName": "Marzec",
    "title": "Publikacja media (Strona)",
    "jrwa": "966.18",
    "activityId": "AehvrjZ6hmuzcGNydgGM",
    "activityName": "Publikacja media (Strona)",
    "plannedCount": 1,
    "completedCount": 0,
    "status": "planned",
    "statusLabel": "Planowane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-38",
    "year": 2026,
    "month": 4,
    "monthName": "Kwiecień",
    "title": "Dystrybucja",
    "jrwa": "966.18",
    "activityId": "FcAXA6DDS8yv3MXwRuXO",
    "activityName": "Dystrybucja",
    "plannedCount": 1,
    "completedCount": 1,
    "status": "done",
    "statusLabel": "Wykonane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-41",
    "year": 2026,
    "month": 4,
    "monthName": "Kwiecień",
    "title": "Dystrybucja",
    "jrwa": "966.3",
    "activityId": "FcAXA6DDS8yv3MXwRuXO",
    "activityName": "Dystrybucja",
    "plannedCount": 1,
    "completedCount": 0,
    "status": "planned",
    "statusLabel": "Planowane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-32",
    "year": 2026,
    "month": 4,
    "monthName": "Kwiecień",
    "title": "Konkurs (quiz)",
    "jrwa": "966.1",
    "activityId": "aFuBdGdK1lOqoMdldAoG",
    "activityName": "Konkurs (quiz)",
    "plannedCount": 1,
    "completedCount": 0,
    "status": "done",
    "statusLabel": "Wykonane",
    "manuallyCompleted": true,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-43",
    "year": 2026,
    "month": 4,
    "monthName": "Kwiecień",
    "title": "Konkurs (quiz)",
    "jrwa": "966.4",
    "activityId": "aFuBdGdK1lOqoMdldAoG",
    "activityName": "Konkurs (quiz)",
    "plannedCount": 1,
    "completedCount": 1,
    "status": "done",
    "statusLabel": "Wykonane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-33",
    "year": 2026,
    "month": 4,
    "monthName": "Kwiecień",
    "title": "Prelekcja (warsztat)",
    "jrwa": "966.1",
    "activityId": "gW1kLj7owM5ebXSkmndz",
    "activityName": "Prelekcja (warsztat)",
    "plannedCount": 1,
    "completedCount": 0,
    "status": "planned",
    "statusLabel": "Planowane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-34",
    "year": 2026,
    "month": 4,
    "monthName": "Kwiecień",
    "title": "Prelekcja (warsztat)",
    "jrwa": "966.12",
    "activityId": "gW1kLj7owM5ebXSkmndz",
    "activityName": "Prelekcja (warsztat)",
    "plannedCount": 1,
    "completedCount": 0,
    "status": "planned",
    "statusLabel": "Planowane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-39",
    "year": 2026,
    "month": 4,
    "monthName": "Kwiecień",
    "title": "Prelekcja (warsztat)",
    "jrwa": "966.18",
    "activityId": "gW1kLj7owM5ebXSkmndz",
    "activityName": "Prelekcja (warsztat)",
    "plannedCount": 1,
    "completedCount": 0,
    "status": "planned",
    "statusLabel": "Planowane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-42",
    "year": 2026,
    "month": 4,
    "monthName": "Kwiecień",
    "title": "Prelekcja (warsztat)",
    "jrwa": "966.3",
    "activityId": "gW1kLj7owM5ebXSkmndz",
    "activityName": "Prelekcja (warsztat)",
    "plannedCount": 1,
    "completedCount": 2,
    "status": "done",
    "statusLabel": "Wykonane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-44",
    "year": 2026,
    "month": 4,
    "monthName": "Kwiecień",
    "title": "Prelekcja (warsztat)",
    "jrwa": "966.4",
    "activityId": "gW1kLj7owM5ebXSkmndz",
    "activityName": "Prelekcja (warsztat)",
    "plannedCount": 1,
    "completedCount": 0,
    "status": "planned",
    "statusLabel": "Planowane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-46",
    "year": 2026,
    "month": 4,
    "monthName": "Kwiecień",
    "title": "Prelekcja (warsztat)",
    "jrwa": "966.5",
    "activityId": "gW1kLj7owM5ebXSkmndz",
    "activityName": "Prelekcja (warsztat)",
    "plannedCount": 1,
    "completedCount": 3,
    "status": "done",
    "statusLabel": "Wykonane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-47",
    "year": 2026,
    "month": 4,
    "monthName": "Kwiecień",
    "title": "Prelekcja (warsztat)",
    "jrwa": "966.6",
    "activityId": "gW1kLj7owM5ebXSkmndz",
    "activityName": "Prelekcja (warsztat)",
    "plannedCount": 1,
    "completedCount": 0,
    "status": "planned",
    "statusLabel": "Planowane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-35",
    "year": 2026,
    "month": 4,
    "monthName": "Kwiecień",
    "title": "Publikacja media (Strona)",
    "jrwa": "966.12",
    "activityId": "AehvrjZ6hmuzcGNydgGM",
    "activityName": "Publikacja media (Strona)",
    "plannedCount": 1,
    "completedCount": 6,
    "status": "done",
    "statusLabel": "Wykonane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-40",
    "year": 2026,
    "month": 4,
    "monthName": "Kwiecień",
    "title": "Publikacja media (Strona)",
    "jrwa": "966.18",
    "activityId": "AehvrjZ6hmuzcGNydgGM",
    "activityName": "Publikacja media (Strona)",
    "plannedCount": 1,
    "completedCount": 0,
    "status": "planned",
    "statusLabel": "Planowane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-48",
    "year": 2026,
    "month": 4,
    "monthName": "Kwiecień",
    "title": "Publikacja media (Strona)",
    "jrwa": "966.6",
    "activityId": "AehvrjZ6hmuzcGNydgGM",
    "activityName": "Publikacja media (Strona)",
    "plannedCount": 1,
    "completedCount": 0,
    "status": "planned",
    "statusLabel": "Planowane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-36",
    "year": 2026,
    "month": 4,
    "monthName": "Kwiecień",
    "title": "Sprawozdanie (z programu, miernik, tytoń)",
    "jrwa": "966.12",
    "activityId": "TAbBvoLS82SYgxRFr41M",
    "activityName": "Sprawozdanie (z programu, miernik, tytoń)",
    "plannedCount": 1,
    "completedCount": 0,
    "status": "planned",
    "statusLabel": "Planowane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-45",
    "year": 2026,
    "month": 4,
    "monthName": "Kwiecień",
    "title": "Sprawozdanie (z programu, miernik, tytoń)",
    "jrwa": "966.4",
    "activityId": "TAbBvoLS82SYgxRFr41M",
    "activityName": "Sprawozdanie (z programu, miernik, tytoń)",
    "plannedCount": 1,
    "completedCount": 0,
    "status": "planned",
    "statusLabel": "Planowane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-37",
    "year": 2026,
    "month": 4,
    "monthName": "Kwiecień",
    "title": "Stoisko edukacyjno-informacyjne",
    "jrwa": "966.12",
    "activityId": "lOSlwqCEkIZqISCcFmnj",
    "activityName": "Stoisko edukacyjno-informacyjne",
    "plannedCount": 1,
    "completedCount": 0,
    "status": "planned",
    "statusLabel": "Planowane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-51",
    "year": 2026,
    "month": 5,
    "monthName": "Maj",
    "title": "Dystrybucja",
    "jrwa": "966.6",
    "activityId": "FcAXA6DDS8yv3MXwRuXO",
    "activityName": "Dystrybucja",
    "plannedCount": 1,
    "completedCount": 0,
    "status": "planned",
    "statusLabel": "Planowane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-52",
    "year": 2026,
    "month": 5,
    "monthName": "Maj",
    "title": "Konkurs (quiz)",
    "jrwa": "966.6",
    "activityId": "aFuBdGdK1lOqoMdldAoG",
    "activityName": "Konkurs (quiz)",
    "plannedCount": 1,
    "completedCount": 1,
    "status": "done",
    "statusLabel": "Wykonane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-49",
    "year": 2026,
    "month": 5,
    "monthName": "Maj",
    "title": "Prelekcja (warsztat)",
    "jrwa": "966.4",
    "activityId": "gW1kLj7owM5ebXSkmndz",
    "activityName": "Prelekcja (warsztat)",
    "plannedCount": 1,
    "completedCount": 0,
    "status": "planned",
    "statusLabel": "Planowane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-50",
    "year": 2026,
    "month": 5,
    "monthName": "Maj",
    "title": "Prelekcja (warsztat)",
    "jrwa": "966.5",
    "activityId": "gW1kLj7owM5ebXSkmndz",
    "activityName": "Prelekcja (warsztat)",
    "plannedCount": 1,
    "completedCount": 6,
    "status": "done",
    "statusLabel": "Wykonane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-53",
    "year": 2026,
    "month": 5,
    "monthName": "Maj",
    "title": "Prelekcja (warsztat)",
    "jrwa": "966.6",
    "activityId": "gW1kLj7owM5ebXSkmndz",
    "activityName": "Prelekcja (warsztat)",
    "plannedCount": 1,
    "completedCount": 1,
    "status": "done",
    "statusLabel": "Wykonane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-54",
    "year": 2026,
    "month": 5,
    "monthName": "Maj",
    "title": "Publikacja media (Strona)",
    "jrwa": "966.6",
    "activityId": "AehvrjZ6hmuzcGNydgGM",
    "activityName": "Publikacja media (Strona)",
    "plannedCount": 1,
    "completedCount": 6,
    "status": "done",
    "statusLabel": "Wykonane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-56",
    "year": 2026,
    "month": 6,
    "monthName": "Czerwiec",
    "title": "Dystrybucja",
    "jrwa": "966.14",
    "activityId": "FcAXA6DDS8yv3MXwRuXO",
    "activityName": "Dystrybucja",
    "plannedCount": 1,
    "completedCount": 2,
    "status": "done",
    "statusLabel": "Wykonane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-66",
    "year": 2026,
    "month": 6,
    "monthName": "Czerwiec",
    "title": "Dystrybucja",
    "jrwa": "966.6",
    "activityId": "FcAXA6DDS8yv3MXwRuXO",
    "activityName": "Dystrybucja",
    "plannedCount": 1,
    "completedCount": 0,
    "status": "planned",
    "statusLabel": "Planowane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-57",
    "year": 2026,
    "month": 6,
    "monthName": "Czerwiec",
    "title": "Konkurs (quiz)",
    "jrwa": "966.14",
    "activityId": "aFuBdGdK1lOqoMdldAoG",
    "activityName": "Konkurs (quiz)",
    "plannedCount": 1,
    "completedCount": 0,
    "status": "done",
    "statusLabel": "Wykonane",
    "manuallyCompleted": true,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-67",
    "year": 2026,
    "month": 6,
    "monthName": "Czerwiec",
    "title": "Konkurs (quiz)",
    "jrwa": "966.6",
    "activityId": "aFuBdGdK1lOqoMdldAoG",
    "activityName": "Konkurs (quiz)",
    "plannedCount": 1,
    "completedCount": 0,
    "status": "planned",
    "statusLabel": "Planowane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-58",
    "year": 2026,
    "month": 6,
    "monthName": "Czerwiec",
    "title": "Pismo (list intencyjny)",
    "jrwa": "966.14",
    "activityId": "yyiNOcRBIps8O4GYDxWV",
    "activityName": "Pismo (list intencyjny)",
    "plannedCount": 1,
    "completedCount": 0,
    "status": "planned",
    "statusLabel": "Planowane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-59",
    "year": 2026,
    "month": 6,
    "monthName": "Czerwiec",
    "title": "Prelekcja (warsztat)",
    "jrwa": "966.14",
    "activityId": "gW1kLj7owM5ebXSkmndz",
    "activityName": "Prelekcja (warsztat)",
    "plannedCount": 1,
    "completedCount": 0,
    "status": "planned",
    "statusLabel": "Planowane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-63",
    "year": 2026,
    "month": 6,
    "monthName": "Czerwiec",
    "title": "Prelekcja (warsztat)",
    "jrwa": "966.4",
    "activityId": "gW1kLj7owM5ebXSkmndz",
    "activityName": "Prelekcja (warsztat)",
    "plannedCount": 1,
    "completedCount": 1,
    "status": "done",
    "statusLabel": "Wykonane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-64",
    "year": 2026,
    "month": 6,
    "monthName": "Czerwiec",
    "title": "Prelekcja (warsztat)",
    "jrwa": "966.5",
    "activityId": "gW1kLj7owM5ebXSkmndz",
    "activityName": "Prelekcja (warsztat)",
    "plannedCount": 1,
    "completedCount": 3,
    "status": "done",
    "statusLabel": "Wykonane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-60",
    "year": 2026,
    "month": 6,
    "monthName": "Czerwiec",
    "title": "Publikacja media (Strona)",
    "jrwa": "966.14",
    "activityId": "AehvrjZ6hmuzcGNydgGM",
    "activityName": "Publikacja media (Strona)",
    "plannedCount": 1,
    "completedCount": 2,
    "status": "done",
    "statusLabel": "Wykonane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-68",
    "year": 2026,
    "month": 6,
    "monthName": "Czerwiec",
    "title": "Publikacja media (Strona)",
    "jrwa": "966.6",
    "activityId": "AehvrjZ6hmuzcGNydgGM",
    "activityName": "Publikacja media (Strona)",
    "plannedCount": 1,
    "completedCount": 1,
    "status": "done",
    "statusLabel": "Wykonane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-55",
    "year": 2026,
    "month": 6,
    "monthName": "Czerwiec",
    "title": "Sprawozdanie (z programu, miernik, tytoń)",
    "jrwa": "966.1",
    "activityId": "TAbBvoLS82SYgxRFr41M",
    "activityName": "Sprawozdanie (z programu, miernik, tytoń)",
    "plannedCount": 1,
    "completedCount": 0,
    "status": "done",
    "statusLabel": "Wykonane",
    "manuallyCompleted": true,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-62",
    "year": 2026,
    "month": 6,
    "monthName": "Czerwiec",
    "title": "Sprawozdanie (z programu, miernik, tytoń)",
    "jrwa": "966.18",
    "activityId": "TAbBvoLS82SYgxRFr41M",
    "activityName": "Sprawozdanie (z programu, miernik, tytoń)",
    "plannedCount": 1,
    "completedCount": 0,
    "status": "done",
    "statusLabel": "Wykonane",
    "manuallyCompleted": true,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-69",
    "year": 2026,
    "month": 6,
    "monthName": "Czerwiec",
    "title": "Sprawozdanie (z programu, miernik, tytoń)",
    "jrwa": "966.6",
    "activityId": "TAbBvoLS82SYgxRFr41M",
    "activityName": "Sprawozdanie (z programu, miernik, tytoń)",
    "plannedCount": 1,
    "completedCount": 0,
    "status": "done",
    "statusLabel": "Wykonane",
    "manuallyCompleted": true,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-61",
    "year": 2026,
    "month": 6,
    "monthName": "Czerwiec",
    "title": "Stoisko edukacyjno-informacyjne",
    "jrwa": "966.14",
    "activityId": "lOSlwqCEkIZqISCcFmnj",
    "activityName": "Stoisko edukacyjno-informacyjne",
    "plannedCount": 1,
    "completedCount": 3,
    "status": "done",
    "statusLabel": "Wykonane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-65",
    "year": 2026,
    "month": 6,
    "monthName": "Czerwiec",
    "title": "Wizytacja",
    "jrwa": "966.5",
    "activityId": "1o2RvAo6CkqRPwDH4LZB",
    "activityName": "Wizytacja",
    "plannedCount": 1,
    "completedCount": 0,
    "status": "planned",
    "statusLabel": "Planowane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-70",
    "year": 2026,
    "month": 7,
    "monthName": "Lipiec",
    "title": "Dystrybucja",
    "jrwa": "966.14",
    "activityId": "FcAXA6DDS8yv3MXwRuXO",
    "activityName": "Dystrybucja",
    "plannedCount": 1,
    "completedCount": 3,
    "status": "done",
    "statusLabel": "Wykonane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-71",
    "year": 2026,
    "month": 7,
    "monthName": "Lipiec",
    "title": "Konkurs (quiz)",
    "jrwa": "966.14",
    "activityId": "aFuBdGdK1lOqoMdldAoG",
    "activityName": "Konkurs (quiz)",
    "plannedCount": 1,
    "completedCount": 1,
    "status": "done",
    "statusLabel": "Wykonane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-72",
    "year": 2026,
    "month": 7,
    "monthName": "Lipiec",
    "title": "Pismo (list intencyjny)",
    "jrwa": "966.14",
    "activityId": "yyiNOcRBIps8O4GYDxWV",
    "activityName": "Pismo (list intencyjny)",
    "plannedCount": 1,
    "completedCount": 1,
    "status": "done",
    "statusLabel": "Wykonane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-73",
    "year": 2026,
    "month": 7,
    "monthName": "Lipiec",
    "title": "Prelekcja (warsztat)",
    "jrwa": "966.14",
    "activityId": "gW1kLj7owM5ebXSkmndz",
    "activityName": "Prelekcja (warsztat)",
    "plannedCount": 1,
    "completedCount": 8,
    "status": "done",
    "statusLabel": "Wykonane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-74",
    "year": 2026,
    "month": 7,
    "monthName": "Lipiec",
    "title": "Publikacja media (Strona)",
    "jrwa": "966.14",
    "activityId": "AehvrjZ6hmuzcGNydgGM",
    "activityName": "Publikacja media (Strona)",
    "plannedCount": 1,
    "completedCount": 4,
    "status": "done",
    "statusLabel": "Wykonane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-76",
    "year": 2026,
    "month": 7,
    "monthName": "Lipiec",
    "title": "Sprawozdanie (z programu, miernik, tytoń)",
    "jrwa": "966.8",
    "activityId": "TAbBvoLS82SYgxRFr41M",
    "activityName": "Sprawozdanie (z programu, miernik, tytoń)",
    "plannedCount": 1,
    "completedCount": 1,
    "status": "done",
    "statusLabel": "Wykonane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-77",
    "year": 2026,
    "month": 7,
    "monthName": "Lipiec",
    "title": "Sprawozdanie (z programu, miernik, tytoń)",
    "jrwa": "966.9",
    "activityId": "TAbBvoLS82SYgxRFr41M",
    "activityName": "Sprawozdanie (z programu, miernik, tytoń)",
    "plannedCount": 1,
    "completedCount": 1,
    "status": "done",
    "statusLabel": "Wykonane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-75",
    "year": 2026,
    "month": 7,
    "monthName": "Lipiec",
    "title": "Stoisko edukacyjno-informacyjne",
    "jrwa": "966.14",
    "activityId": "lOSlwqCEkIZqISCcFmnj",
    "activityName": "Stoisko edukacyjno-informacyjne",
    "plannedCount": 1,
    "completedCount": 1,
    "status": "done",
    "statusLabel": "Wykonane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-78",
    "year": 2026,
    "month": 8,
    "monthName": "Sierpień",
    "title": "Dystrybucja",
    "jrwa": "966.14",
    "activityId": "FcAXA6DDS8yv3MXwRuXO",
    "activityName": "Dystrybucja",
    "plannedCount": 1,
    "completedCount": 0,
    "status": "done",
    "statusLabel": "Wykonane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-79",
    "year": 2026,
    "month": 8,
    "monthName": "Sierpień",
    "title": "Prelekcja (warsztat)",
    "jrwa": "966.14",
    "activityId": "gW1kLj7owM5ebXSkmndz",
    "activityName": "Prelekcja (warsztat)",
    "plannedCount": 1,
    "completedCount": 4,
    "status": "done",
    "statusLabel": "Wykonane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-80",
    "year": 2026,
    "month": 8,
    "monthName": "Sierpień",
    "title": "Publikacja media (Strona)",
    "jrwa": "966.14",
    "activityId": "AehvrjZ6hmuzcGNydgGM",
    "activityName": "Publikacja media (Strona)",
    "plannedCount": 1,
    "completedCount": 1,
    "status": "done",
    "statusLabel": "Wykonane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-82",
    "year": 2026,
    "month": 8,
    "monthName": "Sierpień",
    "title": "Sprawozdanie (z programu, miernik, tytoń)",
    "jrwa": "966.3",
    "activityId": "TAbBvoLS82SYgxRFr41M",
    "activityName": "Sprawozdanie (z programu, miernik, tytoń)",
    "plannedCount": 1,
    "completedCount": 1,
    "status": "done",
    "statusLabel": "Wykonane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-83",
    "year": 2026,
    "month": 8,
    "monthName": "Sierpień",
    "title": "Sprawozdanie (z programu, miernik, tytoń)",
    "jrwa": "966.5",
    "activityId": "TAbBvoLS82SYgxRFr41M",
    "activityName": "Sprawozdanie (z programu, miernik, tytoń)",
    "plannedCount": 1,
    "completedCount": 1,
    "status": "done",
    "statusLabel": "Wykonane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-81",
    "year": 2026,
    "month": 8,
    "monthName": "Sierpień",
    "title": "Stoisko edukacyjno-informacyjne",
    "jrwa": "966.14",
    "activityId": "lOSlwqCEkIZqISCcFmnj",
    "activityName": "Stoisko edukacyjno-informacyjne",
    "plannedCount": 1,
    "completedCount": 1,
    "status": "done",
    "statusLabel": "Wykonane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-84",
    "year": 2026,
    "month": 9,
    "monthName": "Wrzesień",
    "title": "Sprawozdanie (z programu, miernik, tytoń)",
    "jrwa": "966.14",
    "activityId": "TAbBvoLS82SYgxRFr41M",
    "activityName": "Sprawozdanie (z programu, miernik, tytoń)",
    "plannedCount": 1,
    "completedCount": 0,
    "status": "planned",
    "statusLabel": "Planowane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-91",
    "year": 2026,
    "month": 10,
    "monthName": "Październik",
    "title": "Dystrybucja",
    "jrwa": "966.9",
    "activityId": "FcAXA6DDS8yv3MXwRuXO",
    "activityName": "Dystrybucja",
    "plannedCount": 1,
    "completedCount": 0,
    "status": "planned",
    "statusLabel": "Planowane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-88",
    "year": 2026,
    "month": 10,
    "monthName": "Październik",
    "title": "Konkurs (quiz)",
    "jrwa": "966.6",
    "activityId": "aFuBdGdK1lOqoMdldAoG",
    "activityName": "Konkurs (quiz)",
    "plannedCount": 1,
    "completedCount": 0,
    "status": "planned",
    "statusLabel": "Planowane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-89",
    "year": 2026,
    "month": 10,
    "monthName": "Październik",
    "title": "Prelekcja (warsztat)",
    "jrwa": "966.6",
    "activityId": "gW1kLj7owM5ebXSkmndz",
    "activityName": "Prelekcja (warsztat)",
    "plannedCount": 1,
    "completedCount": 0,
    "status": "planned",
    "statusLabel": "Planowane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-92",
    "year": 2026,
    "month": 10,
    "monthName": "Październik",
    "title": "Prelekcja (warsztat)",
    "jrwa": "966.9",
    "activityId": "gW1kLj7owM5ebXSkmndz",
    "activityName": "Prelekcja (warsztat)",
    "plannedCount": 1,
    "completedCount": 0,
    "status": "planned",
    "statusLabel": "Planowane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-90",
    "year": 2026,
    "month": 10,
    "monthName": "Październik",
    "title": "Publikacja media (Strona)",
    "jrwa": "966.6",
    "activityId": "AehvrjZ6hmuzcGNydgGM",
    "activityName": "Publikacja media (Strona)",
    "plannedCount": 1,
    "completedCount": 0,
    "status": "planned",
    "statusLabel": "Planowane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-93",
    "year": 2026,
    "month": 10,
    "monthName": "Październik",
    "title": "Publikacja media (Strona)",
    "jrwa": "966.9",
    "activityId": "AehvrjZ6hmuzcGNydgGM",
    "activityName": "Publikacja media (Strona)",
    "plannedCount": 1,
    "completedCount": 0,
    "status": "planned",
    "statusLabel": "Planowane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-85",
    "year": 2026,
    "month": 10,
    "monthName": "Październik",
    "title": "Szkolenie",
    "jrwa": "966.1",
    "activityId": "PYWeKCiKhGLFEMJlX2G4",
    "activityName": "Szkolenie",
    "plannedCount": 1,
    "completedCount": 0,
    "status": "planned",
    "statusLabel": "Planowane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-86",
    "year": 2026,
    "month": 10,
    "monthName": "Październik",
    "title": "Szkolenie",
    "jrwa": "966.4",
    "activityId": "PYWeKCiKhGLFEMJlX2G4",
    "activityName": "Szkolenie",
    "plannedCount": 1,
    "completedCount": 0,
    "status": "planned",
    "statusLabel": "Planowane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-87",
    "year": 2026,
    "month": 10,
    "monthName": "Październik",
    "title": "Szkolenie",
    "jrwa": "966.5",
    "activityId": "PYWeKCiKhGLFEMJlX2G4",
    "activityName": "Szkolenie",
    "plannedCount": 1,
    "completedCount": 0,
    "status": "planned",
    "statusLabel": "Planowane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-97",
    "year": 2026,
    "month": 11,
    "monthName": "Listopad",
    "title": "Konkurs (quiz)",
    "jrwa": "966.6",
    "activityId": "aFuBdGdK1lOqoMdldAoG",
    "activityName": "Konkurs (quiz)",
    "plannedCount": 1,
    "completedCount": 0,
    "status": "planned",
    "statusLabel": "Planowane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-98",
    "year": 2026,
    "month": 11,
    "monthName": "Listopad",
    "title": "Prelekcja (warsztat)",
    "jrwa": "966.6",
    "activityId": "gW1kLj7owM5ebXSkmndz",
    "activityName": "Prelekcja (warsztat)",
    "plannedCount": 1,
    "completedCount": 0,
    "status": "planned",
    "statusLabel": "Planowane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-100",
    "year": 2026,
    "month": 11,
    "monthName": "Listopad",
    "title": "Prelekcja (warsztat)",
    "jrwa": "966.9",
    "activityId": "gW1kLj7owM5ebXSkmndz",
    "activityName": "Prelekcja (warsztat)",
    "plannedCount": 1,
    "completedCount": 0,
    "status": "planned",
    "statusLabel": "Planowane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-99",
    "year": 2026,
    "month": 11,
    "monthName": "Listopad",
    "title": "Publikacja media (Strona)",
    "jrwa": "966.6",
    "activityId": "AehvrjZ6hmuzcGNydgGM",
    "activityName": "Publikacja media (Strona)",
    "plannedCount": 1,
    "completedCount": 0,
    "status": "planned",
    "statusLabel": "Planowane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-94",
    "year": 2026,
    "month": 11,
    "monthName": "Listopad",
    "title": "Szkolenie",
    "jrwa": "966.1",
    "activityId": "PYWeKCiKhGLFEMJlX2G4",
    "activityName": "Szkolenie",
    "plannedCount": 1,
    "completedCount": 0,
    "status": "planned",
    "statusLabel": "Planowane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-95",
    "year": 2026,
    "month": 11,
    "monthName": "Listopad",
    "title": "Szkolenie",
    "jrwa": "966.3",
    "activityId": "PYWeKCiKhGLFEMJlX2G4",
    "activityName": "Szkolenie",
    "plannedCount": 1,
    "completedCount": 0,
    "status": "planned",
    "statusLabel": "Planowane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-96",
    "year": 2026,
    "month": 11,
    "monthName": "Listopad",
    "title": "Szkolenie",
    "jrwa": "966.5",
    "activityId": "PYWeKCiKhGLFEMJlX2G4",
    "activityName": "Szkolenie",
    "plannedCount": 1,
    "completedCount": 0,
    "status": "planned",
    "statusLabel": "Planowane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  },
  {
    "id": "better-oz-schedule-101",
    "year": 2026,
    "month": 12,
    "monthName": "Grudzień",
    "title": "Sprawozdanie (z programu, miernik, tytoń)",
    "jrwa": "966.6",
    "activityId": "TAbBvoLS82SYgxRFr41M",
    "activityName": "Sprawozdanie (z programu, miernik, tytoń)",
    "plannedCount": 1,
    "completedCount": 0,
    "status": "planned",
    "statusLabel": "Planowane",
    "manuallyCompleted": false,
    "programId": null,
    "programName": null,
    "locationId": null,
    "locationName": null,
    "notes": null
  }
];

const JRWA_TOPIC_MAP = {
  "966.1": "tyton",
  "966.12": "tyton",
  "966.14": "inne",
  "966.18": "zdrowie_psychiczne",
  "966.3": "alkohol",
  "966.4": "narkotyki",
  "966.5": "wzw",
  "966.6": "zywienie_i_aktywnosc",
  "966.8": "szczepienia_zakazne",
  "966.9": "higiena"
};

const JRWA_TITLE_MAP = {
  "966.1": "Profilaktyka antynikotynowa i odtytoniowa",
  "966.12": "Światowy Dzień bez Tytoniu (31 maja)",
  "966.14": "Akcje sezonowe (Bezpieczne Wakacje / Bezpieczne Ferie)",
  "966.18": "Zdrowie psychiczne i higiena cyfrowa",
  "966.3": "Profilaktyka alkoholowa i FASD (ARS)",
  "966.4": "Profilaktyka narkotykowa i dopalacze (NSP)",
  "966.5": "Profilaktyka WZW (Podstępne WZW)",
  "966.6": "Zdrowe żywienie i aktywność fizyczna (Trzymaj Formę!)",
  "966.8": "Choroby zakaźne i szczepienia ochronne",
  "966.9": "Higiena osobista, czyste ręce i środowisko"
};

function pad(n) {
  return String(n).padStart(2, "0");
}

function getLastDayOfMonth(year, month) {
  return new Date(year, month, 0).getDate();
}

const convertedSchedules = rawSchedules.map((item) => {
  const y = item.year || 2026;
  const m = item.month || 1;
  const lastDay = getLastDayOfMonth(y, m);
  const eventDate = `${y}-${pad(m)}-01`;
  const endDate = `${y}-${pad(m)}-${pad(lastDay)}`;
  const topic = JRWA_TOPIC_MAP[item.jrwa] || "inne";
  const jrwaDesc = JRWA_TITLE_MAP[item.jrwa] || `JRWA ${item.jrwa}`;

  let status = "zaplanowane";
  if (item.status === "done" || item.status === "wykonane") {
    status = "zrealizowane";
  }

  const isDone = status === "zrealizowane";
  const noteParts = [];
  if (item.completedCount > 0) {
    noteParts.push(`Wykonano: ${item.completedCount} / zaplanowano: ${item.plannedCount}`);
  } else {
    noteParts.push(`Zaplanowano: ${item.plannedCount}`);
  }
  if (item.jrwa) {
    noteParts.push(`JRWA ${item.jrwa} - ${jrwaDesc}`);
  }
  if (item.manuallyCompleted) {
    noteParts.push("Oznaczone jako wykonane ręcznie");
  }

  return {
    id: item.id,
    title: `${item.title} (JRWA ${item.jrwa})`,
    activityTypeCode: item.activityId || undefined,
    activityTypeName: item.activityName || item.title,
    eventDate: eventDate,
    endDate: endDate,
    category: `JRWA ${item.jrwa}`,
    topic: topic,
    jrwa: item.jrwa,
    year: y,
    month: m,
    monthName: item.monthName,
    plannedCount: item.plannedCount,
    completedCount: item.completedCount,
    manuallyCompleted: Boolean(item.manuallyCompleted),
    location: item.locationName || "Powiat myśliborski / PSSE",
    status: status,
    responsiblePerson: "Stanowisko Pracy ds. OZiPZ",
    notes: noteParts.join(" • "),
    createdAt: `${y}-01-01T08:00:00.000Z`,
    updatedAt: "2026-08-28T08:00:00.000Z"
  };
});

const jsonPath = path.join(__dirname, "../src/features/ozipz/data/firebase_migrated_data.json");
const data = JSON.parse(fs.readFileSync(jsonPath, "utf-8"));
data.schedules = convertedSchedules;

fs.writeFileSync(jsonPath, JSON.stringify(data, null, 2), "utf-8");
console.log(`Pomyślnie zmigrowano ${convertedSchedules.length} pozycji harmonogramu do firebase_migrated_data.json!`);
